version: '3.8'

services: 
    # Backend
    imagelisting: 
        container_name: backend
        # image: node:14.12.0
        build: ./ 
        command: npm run start
        working_dir: /usr/src/imagelisting
        environment: 
            NODE_ENV: docker
        ports: 
            - "5000:5000"
        volumes:
            - ./:/usr/src/imagelisting
    
    # PostgresSQL
    postgres:
        build: ./postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ImageListing
            POSTGRES_HOST: postgres
        ports: 
            - "5432:5432"

