BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Download (
	requestDate DATE NOT NULL,
	ImageId int NOT NULL PRIMARY KEY,
	UserId int NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (UserId) REFERENCES UserDetails(UserId)
);

COMMIT;
