BEGIN TRANSACTION; 

CREATE TABLE IF NOT EXISTS Ratings (
	Score int NOT NULL,
	ImageId int NOT NULL PRIMARY KEY,
	UserId INT NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (UserId) REFERENCES UserDetails(ID)
);

COMMIT;