BEGIN TRANSACTION; 

CREATE TABLE IF NOT EXISTS Ratings (
	ID SERIAL PRIMARY KEY NOT NULL,
	Score int NOT NULL,
	ImageId int NOT NULL,
	IpAddress TEXT NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (IpAddress) REFERENCES UserDetails(IpAddress)
);

COMMIT;