CREATE TABLE IF NOT EXISTS ImageDetails (
	ID SERIAL PRIMARY KEY NOT NULL,
	Name TEXT NOT NULL,
	Category TEXT,
	filepath TEXT NOT NULL,
	uploadDate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS UserDetails (
	IpAddress TEXT PRIMARY KEY,
	lastDateUsed DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Ratings (
	ID SERIAL PRIMARY KEY NOT NULL,
	Score int NOT NULL,
	ImageId int NOT NULL,
	IpAddress TEXT NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (IpAddress) REFERENCES UserDetails(IpAddress)
);

CREATE TABLE IF NOT EXISTS Download (
	ID SERIAL PRIMARY KEY NOT NULL,
	requestDate DATE NOT NULL,
	ImageId int NOT NULL,
	IpAddress TEXT NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (IpAddress) REFERENCES UserDetails(IpAddress)
);