CREATE TABLE IF NOT EXISTS ImageDetails (
	ID SERIAL PRIMARY KEY NOT NULL,
	Name TEXT NOT NULL,
	Categories TEXT NOT NULL,
	uploadDate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Ratings (
	ID SERIAL PRIMARY KEY NOT NULL,
	Review int NOT NULL,
	ImageId int NOT NULL,
	UserId int NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (UserId) REFERENCES User(ID)
);

CREATE TABLE IF NOT EXISTS User (
	ID SERIAL PRIMARY KEY NOT NULL,
	IpAddress TEXT,
);

CREATE TABLE IF NOT EXISTS Download (
	ID SERIAL PRIMARY KEY NOT NULL,
	requestDate DATE NOT NULL,
	ImageId int NOT NULL,
	UserId int NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID),
	FOREIGN KEY (UserId) REFERENCES User(ID)
);

CREATE SEQUENCE IF NOT EXISTS ChangeId;