CREATE TABLE IF NOT EXISTS ImageDetails (
	ID SERIAL PRIMARY KEY NOT NULL,
	Name TEXT NOT NULL,
	Date TEXT NOT NULL,
	Size TEXT NOT NULL,
	Description TEXT
);

CREATE TABLE IF NOT EXISTS Ratings (
	ID SERIAL PRIMARY KEY NOT NULL,
	Count int NOT NULL,
	ImageId int NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID)
);

CREATE TABLE IF NOT EXISTS DownloadRequests (
	ID SERIAL PRIMARY KEY NOT NULL,
	Count int NOT NULL,
	ImageId int NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID)
);

CREATE TABLE IF NOT EXISTS Categories (
	Categories TEXT PRIMARY KEY NOT NULL,
	ImageId int NOT NULL,
	FOREIGN KEY (ImageId) REFERENCES ImageDetails(ID)
);

CREATE SEQUENCE IF NOT EXISTS ChangeId;